% This script answers Questions 7a and 7b in ME396 HW Block A.
% C1C Ashlynn Sweet, 20 September 2024

clear all
close all
clc

% ----------------- Question 7a ----------------------
fprintf(['\nIf an iPhone Pro Max was launched out of space and accurately spun ' ...
    'about its first or third principle axis, it would remain mostly stable ' ...
    'and continue to rotate about that axis.\nIf it were spun about its second axis, it would' ...
    ' be unstable and deteriorate into rotation about its first or third axis.'])

% ----------------- Question 7b ----------------------
fprintf(['\nIf an iPhone Pro Max was launched out into space and spun with ' ...
    'flexible solar panels, then it would generate heat and lose energy in ' ...
    'the system because it is no longer a solid body. Once it begins to lose energy,' ...
    'its angular momentum decreases and it no longer has stability, resulting in an unstable spin.'])